language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install mock
  - sudo apt-cache search keybinder
  - sudo apt-get install keybinder python-keybinder
# command to run tests
script:  python azulejo/unittests.py
